language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.3.3

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjson0-dev libjson0 php5-cli php5-dev  liblua5.2-dev


before_script:
    # Compile PHP
    - ./travis/compile.sh

script: 
 - ./travis/build_check.sh

